### ISSUE TITLE
As an examiner, I want to know the motivations of the work so that I can evaluate it properly.

### ISSUE THREAD

**Issue by JJ** [salvacorts/TFG-Parasitic-Metaheuristics#11]
**User Story**

The examiners need to know several things
* Motivation for the system
* Examination of the state of the art
* Definition of clear, reachable and measurable objectives.

**Acceptance criteria**

Discussion of all issues involved in this issue or in person, and eventually writing them in the report.

**Definition of Done**

Introductory chapter to memory completed.

**Comment by salvacorts** [comment]
## Motivation of the system
Today we have an incredible amount of resources available for computation. A huge amount of them is partially idle all of the time. What about using all these potential resources to help science?

This project aims to take advantage of this opportunity providing a common platform to deploy distributed evolutionary algorithms and enabling both tech-savvy and non-tech-savvy people to contribute to solving problems with their machines.

Since the participants of this platform will be heterogeneous and short-living, we need a scalable design that enables us to deal with nodes that can disappear without previous notice and that can have an important performance difference between each other, or even being implemented in different languages.

## State of the art
There are several projects that take advantage of users computers to contribute to solving problems such as: 
- [Help a Scientist](https://chrome.google.com/webstore/detail/help-a-scientist/bplkoafhogcpnogadljgjecpnfhhbbpc?ref=producthunt)
- [pybossa](https://pybossa.com/)
- [BIONIC](https://boinc.berkeley.edu/)

There are various papers about evolutionary algorithms, some of them are:
- [Peer-to-peer evolutionary algorithms with adaptive autonomous selection](https://dl.acm.org/citation.cfm?doid=1276958.1277225)
- [Distribued Evolutionary Computation using REST](https://www.researchgate.net/publication/51893284_Distributed_Evolutionary_Computation_using_REST)
- [Designing and Modeling a Browser-Based Distributed Evolutionary Computation System](https://dl.acm.org/citation.cfm?doid=2739482.2768465)

## Objectives

- Provide a browser-based interface to contribute to solving problems in a way that the amount of effort the user needs to invest in order to start contributing is minimized.  

- Design a common middleware to communicate nodes in the same local network (e.g. cloud) to avoid single points of failure as well as providing a scalable P2P design. I.e. Design how nodes communicate with each other without a central server that coordinates them.

- Use this platform to run some evolutionary metaheuristics in order to benchmark it against traditional non-distributed implementations.

- A nice extra to have would be the functionality to able to dynamically upload problems to the system so on one hand researchers can submit new projects and users can select which project to contribute to from a catalogue of available problems. 

- Another nice to have extra would be the gamification of the contribution process for the browser-based users in order to maximize the amount of time they invest and to create competition between users in order to promote the contribution between users and promoting the problem itself.

----
### TODO
- [ ] Develop these sections in the documentation

**Comment by salvacorts** [comment]
I've created a system network diagram to show how I see the system

[Check it out here](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7V1bd6O2Fv41eYyXJO6PuTQ9PWu6Oj3Trnb6MguDbHMGIxfkOOmvr8TFWCBjYoTBCXmIjUAybL5935JutIf1y4%2Bxu1n9THwc3iDgv9xojzcIIQeY7IO3vGYt0DFg1rKMAz9vKxu%2BBP%2FgvBHkrdvAx4lwISUkpMFGbPRIFGGPCm1uHJOdeNmChOKvbtwlrjV88dyw3vpH4NNV3goBKE%2F8BwfLVf7TtpGfmLve92VMtlH%2BezdIW6R%2F2em1W4yVX5%2BsXJ%2FsDpq0H260h5gQmn1bvzzgkBO3IFvW7%2BnI2f19xziibTr8%2BevX38HW9Hd%2FEOv1J%2BNX%2Bu3Hf24h0LNxnt1wi4sHSW%2BXvhYkYne%2B4V8jQtnH%2FW4VUPxl43q8bcdgwdpWdB2yI8i%2BlnT5ZUvDIMJ5u%2B%2FG339hvQLKoQJmwGCNiyAMH0hI4vSXCgJq9%2FlN4Zjil6PPC%2FdUZPDEZI1p%2FMouyTtYBcJyZN5CM3%2B0XfmeteI1rw5eMWvN8ZVja7kfvKQv%2B5KT%2BA3kRi2onZIO%2BznVThC7Qj8MfQNbrD2hMfmOD844pqW5phrKQmAYImmRZtZJa0tIa6C%2BSAud90HaKmhtq0ZZQwZaHfQGWtgvZX0X2wtPRlnTs%2FFckTiAwBFBa%2BpaS3Fg9EZZ8C4oazkiYS1jaMIWd3BAR%2BwztZ8fkpiuyJJEbvhD2XpfUhqwI4%2BsAy%2F%2FXl7%2FiZBNTuv%2FY0pfc3vG3VIivgn8EtA%2F8%2B78%2B9dU51lGfvj4cnDu8bU4iNjDp71mRnH49fBc2S09Evp9xnHAqIfjvHFvb6QH1I3pHTeXUj3OlXLW9hRwypbX5A9kp6P6RQ8vdJOEk4M35l1gdnTQIUNZYUUhCR4NbPu6DI82mmtmKUP5y2pGI3u3ZBt7uAkEOX%2Bzx1pi2sSGcnjHOHRp8CzeiHqommOBKlQC1RmwJrT2iVZjULTaY0FrjrsCr41gncDVFlzQ7IiutCujlft6cMGGBBFNDkb%2BzBsOXDUkmmZQAxWkZiOWuN3fWgcoOxOU3zOUkT0KKNsXgLIzGhtCNHdbmxC2Nqy5C81eOAMAA%2BCFjDMAgI%2F3Dx%2FR3nWssWAVnoNVOLix%2B7Gw2tXaPUuIQ00TpbiRx4r6leIjsq1Re4vkmCcIT3DGxATtrXJrCC4wbSQwgZZbzE9HrjeKzJ%2F8%2Bp6YZkRWvHUW07AnEFRKeTyplPfkGJiWwB261sxNzAfWmjr05BTnv9lXRmKxwKYnzUj4ljMH4EZJRsLUxSyabqFZPScBLUlOAup95SRMUKPkaUnlbePnPal7ElsZ97cTW%2Bygs%2BQppYjZRoosbA%2FLITO3Dd0AoujKf7OUW0CtlEEthYw2pI9ljif9NbMFpXjKzZLgq1SVop7cG5tq1KQXkySRo7V6iQiuEs6wFZ5dBEBqXteTsk8ApCLQd5PVnutrinoANA%2Bac0CnVdKCRFQwL0zzgZsXXIsEnhvehcEyYucoh%2B%2B%2B9ZM7x%2BFnkgQ0IPzsnFBK1uyCsHLCY4TlELp383H2DQeQJ1m108O%2BTg3U3%2F1D%2Bid997YN73kUbBm7foDLx8kFWtH8GMRs9Oy2Is6YUsgVFVvrlyUv25tFmO5I%2FD2Zhe4mo4ECLYtsMe9v6xIdC5y6jjX7UrHG8M7A4Ha9eu2qUN6MOw2FTBHQSK9UVFYdXqvx%2Bn4s9BYG%2BiQNW0rDHese4iT5tiY%2BXiuSilAEhenIpKLE87CNnqRii5rTCTEDIgZCWKlMtOuViZeFjAlrEBmFr3pxR7XRrRy1qjVaqlp9CE0LUSXBYtl2o6qF0Gzs0I%2Butc9hg%2BFzlU1OdCV%2F2d2JrvuqpzzqxsjzpVzsATgNDZLFgbotBkNtzWpmtWoHTe%2Bf04zJRlFmo2w8RXZJVUjbALWzS6y%2BHHxbAhMzpFwMBc%2Fs65Kmj541ccAIEDL%2F3pLixG2SCpQ7dgGjyUt5sjrKXO2wvycMUwh8ciP2HxZjMmJkw4o%2FxZprPz%2BPJVcd6SwhykFTfisBvxOXv0H2kthHmN6ax0aMg%2FmWBtEyfePshbNLAiZpwJzPuuR9j92RGsq3fK6KmGB4pyLTinyY89oh0%2BZNNcavSpZ14PupipflvES1r4D9qvk%2FJ8%2F%2FiSkss859vU2x07TO5tAYTCAleQTB0Nmnyw9NHVn287QHIJhTCo0U2DbUDwfNXOW2xkAQEwux4QSxniA2aDpJHxHE3h7EUDtFsEUQZNBi%2F%2FaQ6pow6Db3fEpRqnNfnoOYbt3wG7Mwn9MHUOHK6GJQnomg%2BrR6CGX1QP1ZU90L4ceg6pQElK5O1bVOZA6r6q7aYB%2B%2FdrpYOrtb0OScwsO%2BqiJAdQLNqWkCisq4RhF0HlwcoUGm01TLcW8LpXosBF3rgIBRYYMeYtBwKq0YtxWnmeOz4vTupbZjsOLeOHfrSr3Jtpm6gb3JKRk2bjmEDFEOIUm5zmWlUDHzTjpLR2XRTae4u6qS2LfLmRauomBSHtq7p6p8VAoo8yrcSqMujw51Xv5Khl9fYpyTlQbBy6BJHaM5DDHhZXx4QUPixRzNcjbqcs61wIfq6SDHw6b9rwA1UhQPM9HbqSyDAIGwdsjJ65GFKhzUR6zDnHyMUfsYulWZwj64jwGt05ApSBSs01X379PPu2RTvju3OFgEL1xan8aNHG6S%2Bq38Rx9XlPK9A%2B7446KntDWZYY8N7c5IvGRtxhLs7iz8F7Y%2BRRY24H%2B3f9m%2F3P%2FvR2f3NX2OJ%2FCiOYyOT8maiU72mQ2JDD6owYdl%2F3a73Qwn3ophCM%2BYvskaN7e8co6%2FZH643YTE9ZP0OwKc6dgXXvbHPqJlEL3chkwz3SZ%2FbxkwZptoqQY8RnUROlhHjyEBT38LXctCq0cLNxWXXKoZ5SEkW5%2Bd9TF7p6%2Fr9A0fqVM8q67zZLnml50bM5ABsmD%2FIsI3zUDAczfuPMRFM4PhehsxbhHLNrHr8Q9CV01Vmx%2BmsNKuZhckYeR9FeVF6pq1c5b%2BaphvNQqTV7R3P0ZhAGo9GWTQEHNRSjwCvPWVwuheEPeu8KYdkYkXKkSplyAoBFDmSu9l1v5QiZ9%2BZoHCuwVS51ls3UKJ3WtZRpEKUa0bx5hubQ%2BprnGabr7JlG69GXUoBNY2xUKgvt3Ypes%2Bui81NAYjXXn17igF0cUCxt0E0RSTHbkgQrXIwQgEUXMyfjhXbi%2BIRlCNdtwCF%2BzpQdNayLqK0IE%2BTVu5HsXXGlLDKr4WmaVJ8Y1L8Q2u94zmaby9FhWp03PTIqHHhNHoY5pGc%2BX%2FlQCw77Kkdw3AgWOhzWVyVwLASQJ2AeCwdeDNrsCVAHCSgF0AOKgvap4T%2B7gAHt%2Ful55T13vVy9O2RthA69NW9zIzTuzWBE3Q1KGfKl4kWw9xcpxvxuM4Q6dSiVm4rcM5zsg5DZqpjncUdbxwX5FbzA1AdfhctJBXV7ww%2FBhyoMqLMa4h26DBq%2FBx9e5TwcaQbfgQ9T7tITVotqG4zcloGq3RVKv3GTzbYHZfSa2jpzmCAIPS%2FLxKwXMpuSP3%2FTQowtUClW15sgfIezU4kdVlr6BTgXP2hLWB3rzPmVVxbuEJ57bmDcMLOLdm93V6lQV3uleYf7gAj5ot%2FCRYrARakK2fx221kI1p98NutW0CT%2Bz87UDY6fpxxqrMKValzuzKzK1vCSVxFqBRYHaZ1RnnhfYRdnsxJFZXVd%2Bps7pahKomzLTFjEsZyQOKv%2FlBslKFGVH0GGZ9s0vZRNpiPrhyxFiyzS4vtUPQb7HrfU%2F31GEt7prjLfvPWn4OmCaPL7OxzxcmFtLZ4ftZ4uJmPi5v22XUTL9vYjIP8Zp%2FfSVb3kHcA4jPL2fG0bTfD%2F%2FNvqalm1rFHIHOTLJ1rC2RwEVNrvqlo9Fb2Onq121A5%2FDitJLDYCwDUWXn3Fvk2HUFJNNAve1Bb8umE17xHnXoDA6Y9qj7KAwIKvltB9T577Kb1Nkt%2FEzpCniymOrx%2BGv3WEs1XnvTMvZSfxktk8EdIy9WxT65hcW2R2%2BNvNjw1EhHIi%2BqYhF23a%2F84ZmEW%2B5cuSlJ78IliZk8WbfgXWZrB%2F%2Bkujt7kXk8iF1t3N8Yj5xrt5Qk%2BV4SB0wc4gWVsHDmqSaMdZlc%2By2NVd7qavjVRlXKSwoKoC7z2Pri1yLK8GZ%2B7ZM3z1plYzSMaaniy%2BpAPbOlU8%2FMHmdL4EbcrP9CXe6evmsmLbywQx51LsqjLXZGUcujCisXRsOWmiq2rA7UN1vWPZq7KGKmpIczd%2FpdMV8ZdSnIrUvYT7breX8rr4KL60gADIAXMv4DAD7eP1wh%2F9lquK8yTM%2B8B0FdJ37OorWpW7wg8dpNcwLviwurKlDCgtplWfD4CrZFJCEjXBkrgI0Bm9ORB2hK45llYJBEPNLhzsmWpj0aQ5JimOI9gaXumBp1uKALS%2BwWi4pJdiA8W16%2FdfPBo1sdlu%2FkeiS7rki0V8fpXbbXF3z6ab1hSAiyRIB3yOrvi2erAl6TbORnquFYdhgTLkLLd8cT4z8TH%2FMr%2FgU%3D)

**Comment by salvacorts** [comment]
Issue moved to [salvacorts/TFG-Thesis #2](https://github.com/salvacorts/TFG-Thesis/issues/2) via [**ZenHub**](https://www.zenhub.com/)
